# Generated by Django 5.2.17 on 2026-10-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReminderSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_days_before",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="X: the first reminder goes this many days before the due date.",
                    ),
                ),
                (
                    "every_days_before",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Y: then again every this many days until the due date.",
                    ),
                ),
                (
                    "every_days_overdue",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="Z: after the due date, again every this many days while it is still outstanding.",
                    ),
                ),
            ],
            options={
                "verbose_name": "reminder settings",
                "verbose_name_plural": "reminder settings",
            },
        ),
        migrations.CreateModel(
            name="ReminderSent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("key", models.CharField(max_length=120)),
                ("sent_on", models.DateField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["recipient", "key"],
                        name="compliance__recipie_7cf15f_idx",
                    )
                ],
            },
        ),
    ]
