# Generated by Django 5.2.17 on 2026-10-05 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminderschedule",
            name="registration_every_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Each person's registration is looked up on the register again this many days after the last time (spread by a day either way so the load is even). 1 to 90.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="check professional registrations every (days)",
            ),
        ),
    ]
