# Generated by Django 5.2.17 on 2026-09-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbsenceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("code", models.CharField(max_length=8, unique=True)),
                ("paid", models.BooleanField(default=True)),
                (
                    "uses_pot",
                    models.BooleanField(
                        default=False,
                        help_text="Draws on an allowance. Needs a policy per contract type.",
                    ),
                ),
                ("needs_approval", models.BooleanField(default=True)),
                (
                    "self_certified",
                    models.BooleanField(
                        default=False,
                        help_text="The employee records it themselves, after the fact.",
                    ),
                ),
                (
                    "calendar_label",
                    models.CharField(
                        default="Away",
                        help_text="What colleagues see on the calendar: Leave, Sick, Away.",
                        max_length=20,
                    ),
                ),
                ("payroll_reportable", models.BooleanField(default=False)),
                (
                    "health_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Category and dates are restricted to HR admins and the line manager.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
    ]
