# Generated by Django 5.2.17 on 2026-09-28 18:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absence", "0002_seed_types"),
        ("people", "0010_contracttype_min_and_work_email_help"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "weeks_per_year",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.6"),
                        help_text="Entitlement in weeks; multiplied by the contracted weekly amount.",
                        max_digits=4,
                    ),
                ),
                (
                    "leave_year_basis",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed date"),
                            ("anniversary", "Anniversary of start"),
                        ],
                        default="fixed",
                        max_length=11,
                    ),
                ),
                ("year_start_month", models.PositiveSmallIntegerField(default=4)),
                ("year_start_day", models.PositiveSmallIntegerField(default=1)),
                (
                    "carry_over_max_weeks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "carry_over_expires_after_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rounding",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.25"),
                        help_text="Entitlements and costs are rounded to this step: 0.25 hour, 0.5 session.",
                        max_digits=3,
                    ),
                ),
                (
                    "bank_holiday_handling",
                    models.CharField(
                        choices=[
                            ("closed", "Practice closed, not charged"),
                            ("pot", "Pro-rated bank holiday pot"),
                            ("annual", "Included in annual leave"),
                        ],
                        default="closed",
                        max_length=6,
                    ),
                ),
                (
                    "toil_expires_after_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "absence_type",
                    models.ForeignKey(
                        limit_choices_to={"uses_pot": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="absence.absencetype",
                    ),
                ),
                (
                    "contract_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="people.contracttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "policies",
                "ordering": ["contract_type", "absence_type", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="PolicyTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("after_years", models.PositiveSmallIntegerField()),
                ("extra_weeks", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="absence.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["after_years"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "after_years"), name="one_tier_per_years"
                    )
                ],
            },
        ),
    ]
