# Generated by Django 5.2.17 on 2026-09-28 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absence", "0004_seed_policies"),
        ("people", "0010_contracttype_min_and_work_email_help"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosedDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("reason", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=9,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_half", models.CharField(blank=True, default="", max_length=2)),
                ("end_half", models.CharField(blank=True, default="", max_length=2)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "cost_units",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_comment",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("illness", "Illness"),
                            ("injury", "Injury"),
                            ("mental", "Mental health"),
                            ("surgery", "Surgery or procedure"),
                            ("pregnancy", "Pregnancy-related"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=9,
                    ),
                ),
                ("self_certified", models.BooleanField(default=False)),
                ("expected_start", models.DateField(blank=True, null=True)),
                ("actual_start", models.DateField(blank=True, null=True)),
                ("expected_return", models.DateField(blank=True, null=True)),
                ("auto_bank_holiday", models.BooleanField(default=False)),
                (
                    "absence_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="absences",
                        to="absence.absencetype",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="absences",
                        to="people.employment",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "absences",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="BankHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=60)),
                (
                    "nation",
                    models.CharField(
                        default="EW", help_text="EW, S or NI", max_length=2
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "nation"), name="one_holiday_per_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Pot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_start", models.DateField()),
                ("year_end", models.DateField()),
                ("unit", models.CharField(max_length=8)),
                (
                    "absence_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pots",
                        to="absence.absencetype",
                    ),
                ),
                (
                    "employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pots",
                        to="people.employment",
                    ),
                ),
            ],
            options={
                "ordering": ["-year_start"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("entitlement", "Entitlement"),
                            ("revision", "Entitlement revised"),
                            ("carry_in", "Carried in"),
                            ("expiry", "Expired"),
                            ("booking", "Booked"),
                            ("cancellation", "Cancelled"),
                            ("toil_earned", "TOIL earned"),
                            ("toil_taken", "TOIL taken"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=12,
                    ),
                ),
                ("units", models.DecimalField(decimal_places=2, max_digits=7)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "absence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="absence.absence",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="absence.pot",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ledger entries",
                "ordering": ["date", "id"],
            },
        ),
        migrations.CreateModel(
            name="KitDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "absence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_days",
                        to="absence.absence",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("absence", "date"), name="one_kit_day"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pot",
            constraint=models.UniqueConstraint(
                fields=("employment", "absence_type", "year_start"),
                name="one_pot_per_year",
            ),
        ),
    ]
