# Generated by Django 5.2.17 on 2026-09-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absence", "0007_seed_bank_holiday_policies"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("subject", models.CharField(max_length=200)),
                ("error", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
