# Generated by Django 5.2.17 on 2026-09-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absence", "0008_emailfailure"),
    ]

    operations = [
        migrations.AddField(
            model_name="absence",
            name="chased_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
