# Generated by Django 5.2.17 on 2026-09-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absence", "0010_payrollrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="accrual",
            field=models.CharField(
                choices=[("daily", "Daily"), ("monthly", "Monthly twelfths")],
                default="daily",
                help_text="Daily: earned day by day across the leave year. Monthly twelfths: a twelfth of the year's entitlement for each month of the leave year employed, a part month counting in full.",
                max_length=7,
            ),
        ),
    ]
