# Generated by Django 5.2.17 on 2026-10-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("absence", "0017_zero_expiry_to_blank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="toilclaim",
            options={
                "ordering": ["-day", "-id"],
                "verbose_name": "TOIL claim",
                "verbose_name_plural": "TOIL claims",
            },
        ),
    ]
