# Generated by Django 5.2.17 on 2026-10-04 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("people", "0014_employee_bank"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "positions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty for everyone.",
                        related_name="policies",
                        to="people.positiontitle",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "policies",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=40)),
                ("issued_on", models.DateField()),
                ("sign_within_days", models.PositiveSmallIntegerField(default=14)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.file",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="documents.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "method",
                    models.CharField(
                        choices=[("password", "Password"), ("passkey", "Passkey")],
                        max_length=8,
                    ),
                ),
                ("confirmation_text", models.CharField(max_length=300)),
                ("ip_address", models.CharField(blank=True, default="", max_length=45)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatures",
                        to="people.employee",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatures",
                        to="documents.policyversion",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.UniqueConstraint(
                fields=("policy", "label"), name="one_label_per_policy"
            ),
        ),
        migrations.AddConstraint(
            model_name="signature",
            constraint=models.UniqueConstraint(
                fields=("employee", "version"), name="one_signature_per_version"
            ),
        ),
    ]
