# Generated by Django 5.2.17 on 2026-10-04 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("people", "0014_employee_bank"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("code", models.SlugField(max_length=40, unique=True)),
                (
                    "validity_months",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Blank: a one-off check that never expires.",
                        null=True,
                    ),
                ),
                (
                    "evidence",
                    models.CharField(
                        choices=[
                            ("none", "Nothing to attach"),
                            ("file", "A file"),
                            ("reference", "A reference number"),
                        ],
                        default="none",
                        max_length=9,
                    ),
                ),
                (
                    "remind_person",
                    models.BooleanField(
                        default=False, help_text="Remind the person as well as HR."
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "positions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The titles that need this check.",
                        related_name="check_types",
                        to="people.positiontitle",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done_on", models.DateField(blank=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clear", "Clear"),
                            ("clear_with_notes", "Clear with notes"),
                            ("not_clear", "Not clear"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=60)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "dbs_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("basic", "Basic"),
                            ("standard", "Standard"),
                            ("enhanced", "Enhanced"),
                            ("enhanced_barred", "Enhanced with barred lists"),
                        ],
                        default="",
                        max_length=15,
                    ),
                ),
                ("dbs_update_service", models.BooleanField(default=False)),
                (
                    "awaiting",
                    models.BooleanField(
                        default=False,
                        help_text="Asked of the person; not yet a recorded check.",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checks",
                        to="people.employee",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.file",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checks",
                        to="checks.checktype",
                    ),
                ),
            ],
            options={
                "ordering": ["-done_on", "-id"],
            },
        ),
    ]
