# Generated by Django 5.2.17 on 2026-10-04 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0002_seed_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checktype",
            name="validity_months",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Blank: a one-off check that never expires.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
