# Generated by Django 5.2.17 on 2026-10-05 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0003_validity_months_at_least_one"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Nobody when the register lookups recorded it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
