# Generated by Django 5.2.16 on 2026-09-28 13:44

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                (
                    "preferred_name",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "work_email",
                    models.EmailField(
                        help_text="The login identity. Matched case-insensitively to the login account.",
                        max_length=254,
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("town", models.CharField(blank=True, default="", max_length=60)),
                ("postcode", models.CharField(blank=True, default="", max_length=10)),
                (
                    "ni_number",
                    models.CharField(
                        blank=True, default="", max_length=9, verbose_name="NI number"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "relationship",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("phone", models.CharField(max_length=30)),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="people.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("change", "Change"), ("viewed", "Viewed")],
                        max_length=6,
                    ),
                ),
                ("model", models.CharField(max_length=60)),
                ("object_id", models.PositiveBigIntegerField()),
                ("field", models.CharField(max_length=60)),
                ("before", models.TextField(blank=True, default="")),
                ("after", models.TextField(blank=True, default="")),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "audit entries",
                "ordering": ["-at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["model", "object_id"],
                        name="people_audi_model_f1fce8_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("work_email"),
                name="employee_work_email_ci_unique",
            ),
        ),
    ]
