# Generated by Django 5.2.16 on 2026-09-28 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("display_order", models.PositiveIntegerField(default=100)),
                (
                    "min_present",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Warn an approver when agreeing a request would leave fewer of this team present on a day. Blank means never warn.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Employment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "leaving_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("resigned", "Resigned"),
                            ("retired", "Retired"),
                            ("fixed_term", "End of fixed term"),
                            ("dismissed", "Dismissed"),
                            ("redundancy", "Redundancy"),
                            ("death", "Death in service"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                (
                    "continuous_service_date",
                    models.DateField(
                        help_text="Defaults to the start date. Earlier when reckonable service carries over from elsewhere in the NHS or an earlier spell. Service tiers read this, never the start date."
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employments",
                        to="people.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
