# Generated by Django 5.2.16 on 2026-09-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_team_employment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employment",
            name="continuous_service_date",
            field=models.DateField(
                blank=True,
                help_text="Defaults to the start date. Earlier when reckonable service carries over from elsewhere in the NHS or an earlier spell. Service tiers read this, never the start date.",
            ),
        ),
    ]
