# Generated by Django 5.2.16 on 2026-09-28 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_alter_employment_continuous_service_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("primary", models.BooleanField(default=True)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField(blank=True, null=True)),
                (
                    "employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="people.employment",
                    ),
                ),
                (
                    "line_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="people.employee",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="people.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-primary", "from_date"],
            },
        ),
    ]
