# Generated by Django 5.2.16 on 2026-09-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[("sessions", "Sessions"), ("hours", "Hours")],
                        max_length=8,
                    ),
                ),
                (
                    "full_time_weekly",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What full time is in this unit: 9 sessions, 37.5 hours. FTE is derived from it.",
                        max_digits=5,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=100)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("fixed_term", "Fixed term"),
                        ],
                        default="permanent",
                        max_length=10,
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField(blank=True, null=True)),
                ("weekly_amount", models.DecimalField(decimal_places=2, max_digits=5)),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                (
                    "employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="people.employment",
                    ),
                ),
                (
                    "contract_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="people.contracttype",
                    ),
                ),
            ],
            options={
                "ordering": ["from_date"],
            },
        ),
        migrations.CreateModel(
            name="PayRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField(blank=True, null=True)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("annual", "Annual salary"),
                            ("hourly", "Hourly rate"),
                            ("session", "Per session"),
                        ],
                        max_length=8,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(blank=True, default="", max_length=120)),
                (
                    "employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pay_records",
                        to="people.employment",
                    ),
                ),
            ],
            options={
                "ordering": ["from_date"],
            },
        ),
    ]
