# Generated by Django 5.2.16 on 2026-09-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_contracttype_contract_payrecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={"ordering": ["from_date", "id"]},
        ),
    ]
