# Generated by Django 5.2.16 on 2026-09-28 14:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_alter_contract_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("cycle_weeks", models.PositiveSmallIntegerField(default=1)),
                (
                    "employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patterns",
                        to="people.employment",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="PatternDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("week_in_cycle", models.PositiveSmallIntegerField(default=0)),
                (
                    "am_units",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "pm_units",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="people.workingpattern",
                    ),
                ),
            ],
            options={
                "ordering": ["week_in_cycle", "weekday"],
            },
        ),
        migrations.AddConstraint(
            model_name="workingpattern",
            constraint=models.UniqueConstraint(
                fields=("employment", "effective_from"),
                name="one_pattern_per_employment_per_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="patternday",
            constraint=models.UniqueConstraint(
                fields=("pattern", "weekday", "week_in_cycle"),
                name="one_day_per_pattern",
            ),
        ),
    ]
