# Generated by Django 5.2.16 on 2026-09-28 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Rows written before the column existed get their actor's current
    email — the nearest thing to the email at the time there is."""
    AuditEntry = apps.get_model("people", "AuditEntry")
    for entry in AuditEntry.objects.filter(actor__isnull=False, actor_email="").select_related("actor"):
        AuditEntry.objects.filter(pk=entry.pk).update(actor_email=entry.actor.email)


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_seed_contract_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditentry",
            name="actor_email",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="auditentry",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
