# Generated by Django 5.2.17 on 2026-09-28 17:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0009_auditentry_actor_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracttype",
            name="full_time_weekly",
            field=models.DecimalField(
                decimal_places=2,
                help_text="What full time is in this unit: 9 sessions, 37.5 hours. FTE is derived from it.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="work_email",
            field=models.EmailField(
                help_text="The practice email address, unique whatever its case. Sign-in does not read it: the User field below is what links this record to a login account, and the account's own email is what the rota receives.",
                max_length=254,
            ),
        ),
    ]
