# Generated by Django 5.2.17 on 2026-09-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0010_contracttype_min_and_work_email_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="work_email",
            field=models.EmailField(
                help_text="The practice email address, unique whatever its case. It is the address the rota receives for this person. Sign-in does not read it: the User field below is what links this record to a login account.",
                max_length=254,
            ),
        ),
    ]
