# Generated by Django 5.2.17 on 2026-09-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0011_employee_work_email_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="work_email",
            field=models.EmailField(
                help_text="The practice email address, unique whatever its case. It is the email the rota's read API sends for this person; at sign-in the rota receives the login account's email instead, so keep the two the same. Sign-in does not read it: the User field below is what links this record to a login account.",
                max_length=254,
            ),
        ),
    ]
