# Generated by Django 5.2.17 on 2026-10-04 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0013_positiontitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bank_account_name",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_account_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{8}$", "An account number is eight digits."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_sort_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{2}-\\d{2}-\\d{2}$", "Enter the sort code as NN-NN-NN."
                    )
                ],
            ),
        ),
    ]
