# Generated by Django 5.2.17 on 2026-10-04 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0014_employee_bank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="ni_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2}\\d{6}[A-D]$",
                        "Enter the NI number as two letters, six digits and A, B, C or D, in capitals and without spaces.",
                    )
                ],
                verbose_name="NI number",
            ),
        ),
    ]
