# Generated by Django 5.2.17 on 2026-10-04 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0015_employee_ni_number_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="bank_account_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{8}\\Z", "An account number is eight digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="bank_sort_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{2}-[0-9]{2}-[0-9]{2}\\Z",
                        "Enter the sort code as NN-NN-NN.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="ni_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2}[0-9]{6}[A-D]\\Z",
                        "Enter the NI number as two letters, six digits and A, B, C or D, in capitals and without spaces.",
                    )
                ],
                verbose_name="NI number",
            ),
        ),
    ]
