# Generated by Django 5.2.17 on 2026-10-05 18:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0017_normalise_ni_numbers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("code", models.SlugField(max_length=20, unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Its parser has saved pages to test against; set by the code, not here.",
                    ),
                ),
                (
                    "paused_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Set when three lookups in a row could not read the page.",
                        null=True,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=100)),
                (
                    "positions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The titles that need a registration with this body.",
                        related_name="register_bodies",
                        to="people.positiontitle",
                    ),
                ),
            ],
            options={
                "verbose_name": "register body",
                "verbose_name_plural": "register bodies",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                ("next_check_on", models.DateField()),
                (
                    "last_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clear", "Clear"),
                            ("problem", "Problem"),
                            ("not_found", "Not found"),
                            ("name_mismatch", "Name does not match"),
                            ("unreadable", "Could not read the page"),
                        ],
                        default="",
                        max_length=14,
                    ),
                ),
                (
                    "last_status_text",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "last_name_on_register",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="registers.registerbody",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="people.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["body__display_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Lookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("on_demand", "On demand"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("clear", "Clear"),
                            ("problem", "Problem"),
                            ("not_found", "Not found"),
                            ("name_mismatch", "Name does not match"),
                            ("unreadable", "Could not read the page"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "status_text",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "name_on_register",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("page_hash", models.CharField(blank=True, default="", max_length=64)),
                ("error", models.CharField(blank=True, default="", max_length=80)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lookups",
                        to="registers.registration",
                    ),
                ),
            ],
            options={
                "verbose_name": "registration lookup",
                "ordering": ["-run_at", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("employee", "body"), name="registration_one_per_body"
            ),
        ),
    ]
