# Generated by Django 5.2.17 on 2026-10-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registers", "0002_seed_bodies"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="last_unreadable_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the latest lookup could not read the page; cleared by a readable one.",
                null=True,
            ),
        ),
    ]
