# Generated by Django 5.2.17 on 2026-10-04 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0014_employee_bank"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("starter", "Starter"), ("leaver", "Leaver")],
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gaps",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="One line per set-up problem found when created.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklists",
                        to="people.employment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=10)),
                ("title", models.CharField(max_length=120)),
                ("instruction", models.TextField(blank=True, default="")),
                (
                    "owner",
                    models.CharField(
                        choices=[
                            ("hr", "HR"),
                            ("manager", "Line manager"),
                            ("person", "The person"),
                        ],
                        max_length=7,
                    ),
                ),
                ("due_on", models.DateField()),
                (
                    "due_rule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("before_start", "Days before the start date"),
                            ("after_start", "Days after the start date"),
                            ("before_end", "Days before the leaving date"),
                            ("after_end", "Days after the leaving date"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("link", models.CharField(blank=True, default="", max_length=40)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("done", "Done"),
                            ("not_needed", "Not needed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="onboarding.checklist",
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="people.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["due_on", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("starter", "Starter"), ("leaver", "Leaver")],
                        max_length=7,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("active", models.BooleanField(default=True)),
                (
                    "positions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty for the default of its kind.",
                        related_name="checklist_templates",
                        to="people.positiontitle",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "name"],
            },
        ),
        migrations.AddField(
            model_name="checklist",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="onboarding.checklisttemplate",
            ),
        ),
        migrations.CreateModel(
            name="TemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=10)),
                ("title", models.CharField(max_length=120)),
                ("instruction", models.TextField(blank=True, default="")),
                (
                    "owner",
                    models.CharField(
                        choices=[
                            ("hr", "HR"),
                            ("manager", "Line manager"),
                            ("person", "The person"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "due_rule",
                    models.CharField(
                        choices=[
                            ("before_start", "Days before the start date"),
                            ("after_start", "Days after the start date"),
                            ("before_end", "Days before the leaving date"),
                            ("after_end", "Days after the leaving date"),
                        ],
                        max_length=12,
                    ),
                ),
                ("due_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='"details", "upload:<category>", "sign_policies", "check:<check code>" or blank.',
                        max_length=40,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="onboarding.checklisttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="checklist",
            constraint=models.UniqueConstraint(
                fields=("employment", "kind"), name="one_checklist_per_kind"
            ),
        ),
    ]
