# Generated by Django 5.2.17 on 2026-10-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_seed_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitem",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="A details item: when the person last sent their details (HR's to check from then on).",
                null=True,
            ),
        ),
    ]
